In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [2]:
# Import the dependencies.
import gmaps
import requests
# Import the API key.
from config import g_key

In [3]:
#import WeatherPy_vacation.csv file from part 1 as new DF
hotels_df = pd.read_csv("WeatherPy_vacation.csv")
hotels_df.tail(30)

,Unnamed: 0,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
17,203,Quatre Cocos,MU,77.00,broken clouds,-20.21,57.76,Veranda Palmar Beach Hotel
18,217,Carnarvon,AU,75.20,broken clouds,-24.87,113.63,Hospitality Carnarvon
19,234,Mahebourg,MU,77.00,broken clouds,-20.41,57.70,Shandrani Beachcomber Resort & Spa
20,243,Cap Malheureux,MU,77.00,broken clouds,-19.98,57.61,Pereybere Hotel & Spa
21,262,Babu,CN,76.14,overcast clouds,24.42,111.52,IU Hotel Hezhou Bus Terminal
22,277,Monrovia,LR,78.80,scattered clouds,6.30,-10.80,Eco-Hotel Hall & Restaurant
23,278,Cockburn Town,TC,79.21,scattered clouds,21.46,-71.14,Osprey Beach Hotel
24,298,Bembereke,BJ,76.57,overcast clouds,10.23,2.66,Hotel Bio Guera
25,303,Ormara,PK,79.81,scattered clouds,25.21,64.64,NaN
26,326,Minab,IR,75.20,mist,27.15,57.08,فروشگاه موبایل ترکمانی
27,328,Carutapera,BR,79.12,scattered clouds,-1.20,-46.02,Lidera
28,340,Barahona,DO,77.77,few clouds,18.21,-71.10,Hotel Caribe
29,348,Ballina,AU,77.00,broken clouds,-28.87,153.57,Ramada Hotel & Suites by Wyndham Ballina Byron
30,352,Alcantara,BR,78.80,scattered clouds,-2.41,-44.41,Pousada da Josefa
31,356,Ixtapa,MX,75.20,scattered clouds,20.70,-105.20,Container Inn Puerto Vallarta
32,367,Puerto Escondido,MX,78.98,few clouds,15.85,-97.07,Aldea del Bazar Hotel and Spa
33,375,Noumea,NC,78.01,moderate rain,-22.28,166.46,Hôtel Le Lagon
34,377,Lubbock,US,75.20,few clouds,33.60,-101.83,La Quinta Inn by Wyndham Lubbock - Downtown Ci...
35,384,Garowe,SO,76.35,broken clouds,8.41,48.48,Curubo Hotel
36,410,Dafeng,CN,78.71,overcast clouds,23.45,108.59,Shenglong Hotel
37,451,Yenagoa,NG,76.26,overcast clouds,4.92,6.26,Amba Hotels Limited
38,465,Cayenne,GF,77.00,mist,4.93,-52.33,Hôtel Le Dronmi
39,483,Tutoia,BR,78.98,broken clouds,-2.76,-42.27,Pousada Guará's
40,488,Araouane,ML,79.32,clear sky,18.90,-3.53,NaN
41,519,Jurado,CO,77.67,overcast clouds,7.11,-77.76,NaN
42,526,Sabha,LY,77.22,overcast clouds,27.04,14.43,محطة ام الارانب -سبها مواصلات
43,542,Las Vegas,US,78.80,clear sky,36.17,-115.14,Plaza Hotel & Casino
44,563,Soe,ID,79.12,clear sky,-9.86,124.28,Dena Hotel
45,570,Samba,IN,75.56,overcast clouds,32.57,75.12,"Vishal Guest House, Samba"
46,582,Belmonte,BR,77.00,overcast clouds,-15.86,-38.88,Pousada Monte Carmelo O Pão

In [4]:
hotels_df.dtypes

Unnamed: 0               int64
City                    object
Country                 object
Max Temp               float64
Current Description     object
Lat                    float64
Lng                    float64
Hotel Name              object
dtype: object

In [5]:
#Get Hotels in the Americas
#las_vegas = hotels_df.loc[(hotels_df["Country"] == "US") & (hotels_df["City"] == "Las Vegas")]
#lubbock = hotels_df.loc[(hotels_df["Country"] == "US") & (hotels_df["City"] == "Lubbock")]
#jurado = hotels_df.loc[(hotels_df["Country"] == "CO") & (hotels_df["City"] == "Jurado")]
#san_patricio = hotels_df.loc[(hotels_df["Country"] == "MX") & (hotels_df["City"] == "San Patricio")]
#hotels_df_two
#print(las_vegas)
#print(lubbock)
#print(jurado)
#print(san_patricio)

In [6]:
las_vegas = hotels_df.loc[(hotels_df["Country"] == "US") & (hotels_df["City"] == "Las Vegas")]
las_vegas

,Unnamed: 0,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
43,542,Las Vegas,US,78.8,clear sky,36.17,-115.14,Plaza Hotel & Casino

In [7]:
lubbock = hotels_df.loc[(hotels_df["Country"] == "US") & (hotels_df["City"] == "Lubbock")]
lubbock

,Unnamed: 0,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
34,377,Lubbock,US,75.2,few clouds,33.6,-101.83,La Quinta Inn by Wyndham Lubbock - Downtown Ci...

In [8]:
puerto_escondido = hotels_df.loc[(hotels_df["Country"] == "MX") & (hotels_df["City"] == "Puerto Escondido")]
puerto_escondido

,Unnamed: 0,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
32,367,Puerto Escondido,MX,78.98,few clouds,15.85,-97.07,Aldea del Bazar Hotel and Spa

In [9]:
san_patricio = hotels_df.loc[(hotels_df["Country"] == "MX") & (hotels_df["City"] == "San Patricio")]
san_patricio

,Unnamed: 0,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,21,San Patricio,MX,75.2,clear sky,19.22,-104.7,Hotel Cabo Blanco

In [21]:

City_No = [21,367,377,542]
City = ["San Patricio", "Puerto Escondido", "Lubbock", "Las Vegas"]
Country = ["MX", "MX", "US", "US"]
Max_Temp = [75.2, 78.98, 75.2, 78.8]
Current_Description = ["clear sky", "few clouds", "few clouds", "clear sky"]
Lat = [19.22, 15.85, 33.6, 36.17]
Lng = [-104.7, -97.07, -101.83, -115.14]
Hotel_Name = ["Hotel Cabo Blanco", "Aldea del Bazar Hotel and Spa","La Quinta Inn by Wyndham Lubbock - Downtown Civic Center", "Plaza Hotel & Casino"]
four_cities_df = pd.DataFrame({"City No": City_No, "City": City, "Country": Country, "Max Temp": Max_Temp, "Current Description" : Current_Description, "Lat" : Lat, "Lng": Lng, "Hotel Name": Hotel_Name})
four_cities_df

,City No,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,21,San Patricio,MX,75.20,clear sky,19.22,-104.70,Hotel Cabo Blanco
1,367,Puerto Escondido,MX,78.98,few clouds,15.85,-97.07,Aldea del Bazar Hotel and Spa
2,377,Lubbock,US,75.20,few clouds,33.60,-101.83,La Quinta Inn by Wyndham Lubbock - Downtown Ci...
3,542,Las Vegas,US,78.80,clear sky,36.17,-115.14,Plaza Hotel & Casino

In [11]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [26]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in four_cities.iterrows()]

In [29]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = four_cities_df[["Lat", "Lng"]]
max_temp = four_cities_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [27]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = four_cities_df[["Lat", "Lng"]]
max_temp = four_cities_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))